const items = {
    "item_abyssal_blade": "abyssal blade",
    "item_aegis": "aegis",
    "item_aether_lens": "aether lens",
    "item_ancient_janggo": "ancient janggo",
    "item_arcane_boots": "arcane boots",
    "item_armlet": "armlet",
    "item_assault": "assault",
    "item_banana": "banana",
    "item_basher": "basher",
    "item_belt_of_strength": "belt of strength",
    "item_bfury": "bfury",
    "item_black_king_bar": "black king bar",
    "item_blade_mail": "blade mail",
    "item_blade_of_alacrity": "blade of alacrity",
    "item_blades_of_attack": "blades of attack",
    "item_blight_stone": "blight stone",
    "item_blink": "blink",
    "item_bloodstone": "bloodstone",
    "item_bloodthorn": "bloodthorn",
    "item_boots": "boots",
    "item_boots_of_elves": "boots of elves",
    "item_bottle": "bottle",
    "item_bracer": "bracer",
    "item_branches": "branches",
    "item_broadsword": "broadsword",
    "item_buckler": "buckler",
    "item_butterfly": "butterfly",
    "item_chainmail": "chainmail",
    "item_cheese": "cheese",
    "item_circlet": "circlet",
    "item_clarity": "clarity",
    "item_claymore": "claymore",
    "item_cloak": "cloak",
    "item_courier": "courier",
    "item_crimson_guard": "crimson guard",
    "item_cyclone": "cyclone",
    "item_dagon": "dagon",
    "item_dagon_2": "dagon 2",
    "item_dagon_3": "dagon 3",
    "item_dagon_4": "dagon 4",
    "item_dagon_5": "dagon 5",
    "item_demon_edge": "demon edge",
    "item_desolator": "desolator",
    "item_diffusal_blade": "diffusal blade",
    "item_diffusal_blade_2": "diffusal blade 2",
    "item_dragon_lance": "dragon lance",
    "item_dust": "dust",
    "item_eagle": "eagle",
    "item_echo_sabre": "echo sabre",
    "item_enchanted_mango": "enchanted mango",
    "item_energy_booster": "energy booster",
    "item_ethereal_blade": "ethereal blade",
    "item_faerie_fire": "faerie fire",
    "item_flask": "flask",
    "item_flying_courier": "flying courier",
    "item_force_staff": "force staff",
    "item_gauntlets": "gauntlets",
    "item_gem": "gem",
    "item_ghost": "ghost",
    "item_glimmer_cape": "glimmer cape",
    "item_gloves": "gloves",
    "item_greater_crit": "greater crit",
    "item_greevil_whistle": "greevil whistle",
    "item_greevil_whistle_toggle": "greevil whistle toggle",
    "item_guardian_greaves": "guardian greaves",
    "item_halloween_candy_corn": "halloween candy corn",
    "item_halloween_rapier": "halloween rapier",
    "item_hand_of_midas": "hand of midas",
    "item_headdress": "headdress",
    "item_heart": "heart",
    "item_heavens_halberd": "heavens halberd",
    "item_helm_of_iron_will": "helm of iron will",
    "item_helm_of_the_dominator": "helm of the dominator",
    "item_hood_of_defiance": "hood of defiance",
    "item_hurricane_pike": "hurricane pike",
    "item_hyperstone": "hyperstone",
    "item_infused_raindrop": "infused raindrop",
    "item_invis_sword": "invis sword",
    "item_iron_talon": "iron talon",
    "item_javelin": "javelin",
    "item_lesser_crit": "lesser crit",
    "item_lifesteal": "lifesteal",
    "item_lotus_orb": "lotus orb",
    "item_maelstrom": "maelstrom",
    "item_magic_stick": "magic stick",
    "item_magic_wand": "magic wand",
    "item_manta": "manta",
    "item_mantle": "mantle",
    "item_mask_of_madness": "mask of madness",
    "item_medallion_of_courage": "medallion of courage",
    "item_mekansm": "mekansm",
    "item_mithril_hammer": "mithril hammer",
    "item_mjollnir": "mjollnir",
    "item_monkey_king_bar": "monkey king bar",
    "item_moon_shard": "moon shard",
    "item_mystery_arrow": "mystery arrow",
    "item_mystery_hook": "mystery hook",
    "item_mystery_missile": "mystery missile",
    "item_mystery_toss": "mystery toss",
    "item_mystery_vacuum": "mystery vacuum",
    "item_mystic_staff": "mystic staff",
    "item_necronomicon": "necronomicon",
    "item_necronomicon_2": "necronomicon 2",
    "item_necronomicon_3": "necronomicon 3",
    "item_null_talisman": "null talisman",
    "item_oblivion_staff": "oblivion staff",
    "item_octarine_core": "octarine core",
    "item_ogre_axe": "ogre axe",
    "item_orb_of_venom": "orb of venom",
    "item_orchid": "orchid",
    "item_pers": "pers",
    "item_phase_boots": "phase boots",
    "item_pipe": "pipe",
    "item_platemail": "platemail",
    "item_point_booster": "point booster",
    "item_poor_mans_shield": "poor mans shield",
    "item_power_treads": "power treads",
    "item_present": "present",
    "item_quarterstaff": "quarterstaff",
    "item_quelling_blade": "quelling blade",
    "item_radiance": "radiance",
    "item_rapier": "rapier",
    "item_reaver": "reaver",
    "item_recipe_abyssal_blade": "recipe abyssal blade",
    "item_recipe_aether_lens": "recipe aether lens",
    "item_recipe_ancient_janggo": "recipe ancient janggo",
    "item_recipe_arcane_boots": "recipe arcane boots",
    "item_recipe_armlet": "recipe armlet",
    "item_recipe_assault": "recipe assault",
    "item_recipe_basher": "recipe basher",
    "item_recipe_bfury": "recipe bfury",
    "item_recipe_black_king_bar": "recipe black king bar",
    "item_recipe_blade_mail": "recipe blade mail",
    "item_recipe_bloodstone": "recipe bloodstone",
    "item_recipe_bloodthorn": "recipe bloodthorn",
    "item_recipe_bracer": "recipe bracer",
    "item_recipe_buckler": "recipe buckler",
    "item_recipe_butterfly": "recipe butterfly",
    "item_recipe_crimson_guard": "recipe crimson guard",
    "item_recipe_cyclone": "recipe cyclone",
    "item_recipe_dagon": "recipe dagon",
    "item_recipe_dagon_2": "recipe dagon 2",
    "item_recipe_dagon_3": "recipe dagon 3",
    "item_recipe_dagon_4": "recipe dagon 4",
    "item_recipe_dagon_5": "recipe dagon 5",
    "item_recipe_desolator": "recipe desolator",
    "item_recipe_diffusal_blade": "recipe diffusal blade",
    "item_recipe_diffusal_blade_2": "recipe diffusal blade 2",
    "item_recipe_dragon_lance": "recipe dragon lance",
    "item_recipe_echo_sabre": "recipe echo sabre",
    "item_recipe_ethereal_blade": "recipe ethereal blade",
    "item_recipe_force_staff": "recipe force staff",
    "item_recipe_glimmer_cape": "recipe glimmer cape",
    "item_recipe_greater_crit": "recipe greater crit",
    "item_recipe_guardian_greaves": "recipe guardian greaves",
    "item_recipe_hand_of_midas": "recipe hand of midas",
    "item_recipe_headdress": "recipe headdress",
    "item_recipe_heart": "recipe heart",
    "item_recipe_heavens_halberd": "recipe heavens halberd",
    "item_recipe_helm_of_the_dominator": "recipe helm of the dominator",
    "item_recipe_hood_of_defiance": "recipe hood of defiance",
    "item_recipe_hurricane_pike": "recipe hurricane pike",
    "item_recipe_invis_sword": "recipe invis sword",
    "item_recipe_iron_talon": "recipe iron talon",
    "item_recipe_lesser_crit": "recipe lesser crit",
    "item_recipe_lotus_orb": "recipe lotus orb",
    "item_recipe_maelstrom": "recipe maelstrom",
    "item_recipe_magic_wand": "recipe magic wand",
    "item_recipe_manta": "recipe manta",
    "item_recipe_mask_of_madness": "recipe mask of madness",
    "item_recipe_medallion_of_courage": "recipe medallion of courage",
    "item_recipe_mekansm": "recipe mekansm",
    "item_recipe_mjollnir": "recipe mjollnir",
    "item_recipe_monkey_king_bar": "recipe monkey king bar",
    "item_recipe_moon_shard": "recipe moon shard",
    "item_recipe_necronomicon": "recipe necronomicon",
    "item_recipe_necronomicon_2": "recipe necronomicon 2",
    "item_recipe_necronomicon_3": "recipe necronomicon 3",
    "item_recipe_null_talisman": "recipe null talisman",
    "item_recipe_oblivion_staff": "recipe oblivion staff",
    "item_recipe_octarine_core": "recipe octarine core",
    "item_recipe_orchid": "recipe orchid",
    "item_recipe_pers": "recipe pers",
    "item_recipe_phase_boots": "recipe phase boots",
    "item_recipe_pipe": "recipe pipe",
    "item_recipe_poor_mans_shield": "recipe poor mans shield",
    "item_recipe_power_treads": "recipe power treads",
    "item_recipe_radiance": "recipe radiance",
    "item_recipe_rapier": "recipe rapier",
    "item_recipe_refresher": "recipe refresher",
    "item_recipe_ring_of_aquila": "recipe ring of aquila",
    "item_recipe_ring_of_basilius": "recipe ring of basilius",
    "item_recipe_rod_of_atos": "recipe rod of atos",
    "item_recipe_sange": "recipe sange",
    "item_recipe_sange_and_yasha": "recipe sange and yasha",
    "item_recipe_satanic": "recipe satanic",
    "item_recipe_sheepstick": "recipe sheepstick",
    "item_recipe_shivas_guard": "recipe shivas guard",
    "item_recipe_silver_edge": "recipe silver edge",
    "item_recipe_skadi": "recipe skadi",
    "item_recipe_solar_crest": "recipe solar crest",
    "item_recipe_soul_booster": "recipe soul booster",
    "item_recipe_soul_ring": "recipe soul ring",
    "item_recipe_sphere": "recipe sphere",
    "item_recipe_tranquil_boots": "recipe tranquil boots",
    "item_recipe_travel_boots": "recipe travel boots",
    "item_recipe_travel_boots_2": "recipe travel boots 2",
    "item_recipe_ultimate_scepter": "recipe ultimate scepter",
    "item_recipe_urn_of_shadows": "recipe urn of shadows",
    "item_recipe_vanguard": "recipe vanguard",
    "item_recipe_veil_of_discord": "recipe veil of discord",
    "item_recipe_vladmir": "recipe vladmir",
    "item_recipe_ward_dispenser": "recipe ward dispenser",
    "item_recipe_wraith_band": "recipe wraith band",
    "item_recipe_yasha": "recipe yasha",
    "item_refresher": "refresher",
    "item_relic": "relic",
    "item_ring_of_aquila": "ring of aquila",
    "item_ring_of_basilius": "ring of basilius",
    "item_ring_of_health": "ring of health",
    "item_ring_of_protection": "ring of protection",
    "item_ring_of_regen": "ring of regen",
    "item_river_painter": "river painter",
    "item_river_painter2": "river painter2",
    "item_river_painter3": "river painter3",
    "item_river_painter4": "river painter4",
    "item_river_painter5": "river painter5",
    "item_river_painter6": "river painter6",
    "item_river_painter7": "river painter7",
    "item_robe": "robe",
    "item_rod_of_atos": "rod of atos",
    "item_sange": "sange",
    "item_sange_and_yasha": "sange and yasha",
    "item_satanic": "satanic",
    "item_shadow_amulet": "shadow amulet",
    "item_sheepstick": "sheepstick",
    "item_shivas_guard": "shivas guard",
    "item_silver_edge": "silver edge",
    "item_skadi": "skadi",
    "item_slippers": "slippers",
    "item_smoke_of_deceit": "smoke of deceit",
    "item_sobi_mask": "sobi mask",
    "item_solar_crest": "solar crest",
    "item_soul_booster": "soul booster",
    "item_soul_ring": "soul ring",
    "item_sphere": "sphere",
    "item_staff_of_wizardry": "staff of wizardry",
    "item_stout_shield": "stout shield",
    "item_talisman_of_evasion": "talisman of evasion",
    "item_tango": "tango",
    "item_tango_single": "tango single",
    "item_tome_of_knowledge": "tome of knowledge",
    "item_tpscroll": "tpscroll",
    "item_tranquil_boots": "tranquil boots",
    "item_travel_boots": "travel boots",
    "item_travel_boots_2": "travel boots 2",
    "item_ultimate_orb": "ultimate orb",
    "item_ultimate_scepter": "ultimate scepter",
    "item_urn_of_shadows": "urn of shadows",
    "item_vanguard": "vanguard",
    "item_veil_of_discord": "veil of discord",
    "item_vitality_booster": "vitality booster",
    "item_vladmir": "vladmir",
    "item_void_stone": "void stone",
    "item_ward_dispenser": "ward dispenser",
    "item_ward_observer": "ward observer",
    "item_ward_sentry": "ward sentry",
    "item_wind_lace": "wind lace",
    "item_winter_cake": "winter cake",
    "item_winter_coco": "winter coco",
    "item_winter_cookie": "winter cookie",
    "item_winter_greevil_chewy": "winter greevil chewy",
    "item_winter_greevil_garbage": "winter greevil garbage",
    "item_winter_greevil_treat": "winter greevil treat",
    "item_winter_ham": "winter ham",
    "item_winter_kringle": "winter kringle",
    "item_winter_mushroom": "winter mushroom",
    "item_winter_skates": "winter skates",
    "item_winter_stocking": "winter stocking",
    "item_wraith_band": "wraith band",
    "item_yasha": "yasha",
}